### ISSUE TITLE
Constructor interception feature

### ISSUE THREAD

**Issue by mfkl** [Capgemini/Cauldron#45]
Following up on #44 regarding constructor interception.

> Should I add it before or after base class call…

For my personal use case, I'd need to be able to run code before anything (including the base class call).

 > Should it be around the original constructor body

What's the other option? Inside the actual constructor body? Don't think that changes anything for me either way but other people might prefer the injected code to be run outside of the body?

> Does it make sense to have a try-catch

It does not affect my particular use case, but I'd say yes. To remain consistent with the interception API for methods and properties, for one. And because user code can always throw and they might want to handle it.

**Comment by reflection-emit** [comment]
https://github.com/Capgemini/Cauldron/wiki/Contructor-interception
Coming in the next version

**Comment by mfkl** [comment]
Awesome! Good job.

Cherry on cake would be to able to do conditional base calls (https://code.videolan.org/videolan/libvlcpp/blob/master/vlcpp/MediaDiscoverer.hpp#L92), but that seems hard to do since Attributes can't take Actions as constructors...

**Comment by reflection-emit** [comment]
Hmmm... That should be possible somehow... Let me think about that.
