### ISSUE TITLE
Init method in interceptor pulling in method/property/etc information for use in the interception

### ISSUE THREAD

**Issue by Kazpers** [Capgemini/Cauldron#47]
Ie. pulling in MethodBase and args (for methods) like this:

public void Init(object instance, MethodBase method, object[] args) {
		TestMessages.Record(string.Format("Init: {0} [{1}]", method.DeclaringType.FullName + "." + method.Name, args.Length));
	}

Idea taken from MethodDecorator.Fody, but would be very useful for knowing something about the instance and method/property/anything we are weaving.

**Comment by reflection-emit** [comment]
All 4 kinds of interceptors have the instance (except you are intercepting static), args and MethodBase.
The [IMethodInterceptor](https://capgemini.github.io/Cauldron/netstandard/html/2c72a710-f4ec-4a97-47c5-b73b98c0ae39.htm) has it in the [OnEnter](https://capgemini.github.io/Cauldron/netstandard/html/8fcf4d61-8ab7-b86f-ee0a-d937054a79d2.htm).
The [IPropertyGetterInterceptor](https://capgemini.github.io/Cauldron/netstandard/html/e6ff19aa-45e3-f4b8-3983-05e3768fefce.htm) has it in the [OnGet](https://capgemini.github.io/Cauldron/netstandard/html/0c5d3ae9-686d-c18c-4d79-14e850b23d61.htm)... In this it is part of [PropertyInterceptionInfo](https://capgemini.github.io/Cauldron/netstandard/html/0e919b65-d6b9-2d03-dd29-d4404d1555d8.htm).
The [IPropertySetterInterceptor](https://capgemini.github.io/Cauldron/netstandard/html/dca3879b-58e5-e2bd-f932-e9af8364f3c4.htm) has it in the [OnSet](https://capgemini.github.io/Cauldron/netstandard/html/71d76779-afc8-3f98-847e-e5f92f70b321.htm), also in the PropertyInterceptionInfo.
The [IConstructorInterceptor](https://capgemini.github.io/Cauldron/netstandard/html/953318c2-bf50-a4a6-5c6c-32bc25377add.htm) has it also in the [OnEnter](https://capgemini.github.io/Cauldron/netstandard/html/6becb407-c35c-4c23-e13b-102dcd392f85.htm).

There is also an interface for the property interceptors that force them to move the init to the ctor [IPropertyInterceptorInitialize](https://capgemini.github.io/Cauldron/netstandard/html/0aba377f-eaa7-da22-794b-d19b55568f11.htm).

**Comment by Kazpers** [comment]
Thank you!
