### ISSUE TITLE
Conditional base calls interceptor

### ISSUE THREAD

**Issue by reflection-emit** [Capgemini/Cauldron#49]
Idea taken from #45 

Example:
[https://code.videolan.org/videolan/libvlcpp/blob/master/vlcpp/MediaDiscoverer.hpp#L92](https://code.videolan.org/videolan/libvlcpp/blob/master/vlcpp/MediaDiscoverer.hpp#L92)

**Comment by reflection-emit** [comment]
I am afraid... This is absolutely not possible... I tried, but failed.

**Comment by mfkl** [comment]
Ok, thanks!
