### ISSUE TITLE
Method interceptor inner method interceptor

### ISSUE THREAD

**Issue by juvenull** [Capgemini/Cauldron#56]
I have method1 with interceptor and inner method2 with own interceptor.
Method2 return null always. It's not correct behavior.

ps: use Cauldron.Interception.Fody v2.0.29

**Comment by reflection-emit** [comment]
Hi,

sorry for the late response. That is actually a bug. Can you use the latest beta please. I fixed it there already.

________________________________

Firma: Capgemini Deutschland GmbH
Aufsichtsratsvorsitzender: Antonio Schnieder • Geschäftsführer: Dr. Michael Schulte (Sprecher) • Jost Förster • Dr. Peter Lempp • Dr. Volkmar Varnhagen

Amtsgericht Berlin-Charlottenburg, HRB 98814
This message contains information that may be privileged or confidential and is the property of the Capgemini Group. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by reflection-emit** [comment]
Do you have the same problem with version 3.0.3 still or can I consider this issue as solved?
