### ISSUE TITLE
Add return value to IMethodInterceptor OnExit

### ISSUE THREAD

**Issue by reflection-emit** [Capgemini/Cauldron#62]
What the title says

**Comment by antoniobaiao** [comment]
@reflection-emit  have you any prevision to release this functionality? Thanks

**Comment by reflection-emit** [comment]
Yes...
This is actually a breaking change, because it will change the OnExit parameters.
Because of that I was planing to implement this after my big „dependency cleaning“ task, where I will try to shrink Cauldron to 1 DLL per package.

But... If you say you need this feature, I can implement it this coming weekend and release beta packages for this.

________________________________

Firma: Capgemini Deutschland GmbH
Aufsichtsratsvorsitzender: Antonio Schnieder • Geschäftsführer: Dr. Michael Schulte (Sprecher) • Jost Förster • Dr. Peter Lempp • Dr. Volkmar Varnhagen

Amtsgericht Berlin-Charlottenburg, HRB 98814
This message contains information that may be privileged or confidential and is the property of the Capgemini Group. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by reflection-emit** [comment]
Added in the latest version.
<br/>
Add the following interface to your __IMethodInterceptor__: [IMethodInterceptorOnExit](https://capgemini.github.io/Cauldron/win32/html/T_Cauldron_Interception_IMethodInterceptorOnExit.htm)
